# Preprocessing

* Cyclic time features
* p_num as categorical
* selected features are bg, insulin, cals, steps, hr for the last 1:00 hour
* for training only used data extracted from the test data

**Scoring: 2.4130**

* I stop here with the baseline model because the global model with train data (3.30) performs better

In [1]:
from data import load_data

_, additional_train_data, test_data = load_data()

In [2]:
from pipelines import preprocessing_pipeline, standardization_pipeline

train_data = preprocessing_pipeline.fit_transform(additional_train_data)
train_data.head()

,p_num,hour_sin,hour_cos,bg-1:00,bg-0:55,bg-0:50,bg-0:45,bg-0:40,bg-0:35,bg-0:30,...,cals-0:40,cals-0:35,cals-0:30,cals-0:25,cals-0:20,cals-0:15,cals-0:10,cals-0:05,cals-0:00,bg+1:00
id,,,,,,,,,,,,,,,,,,,,,
p01_test_12,p01,0.461749,0.887011,9.2,9.2,9.5,9.9,10.2,10.2,10.3,...,6.2,5.0,4.8,4.9,4.8,4.8,4.8,4.8,4.9,14.60
p01_test_13,p01,0.480989,0.876727,9.2,9.5,9.9,10.2,10.2,10.3,10.3,...,5.0,4.8,4.9,4.8,4.8,4.8,4.8,4.9,4.8,14.40
p01_test_14,p01,0.500000,0.866025,9.5,9.9,10.2,10.2,10.3,10.3,10.3,...,4.8,4.9,4.8,4.8,4.8,4.8,4.9,4.8,4.9,14.13
p01_test_15,p01,0.518773,0.854912,9.9,10.2,10.2,10.3,10.3,10.3,10.2,...,4.9,4.8,4.8,4.8,4.8,4.9,4.8,4.9,4.9,13.87
p01_test_16,p01,0.537300,0.843391,10.2,10.2,10.3,10.3,10.3,10.2,10.2,...,4.8,4.8,4.8,4.8,4.9,4.8,4.9,4.9,4.9,13.60

In [3]:
train_data = standardization_pipeline.fit_transform(train_data)
train_data.head()

,hour_sin,hour_cos,bg-1:00,bg-0:55,bg-0:50,bg-0:45,bg-0:40,bg-0:35,bg-0:30,bg-0:25,...,p_num_p10,p_num_p11,p_num_p12,p_num_p15,p_num_p16,p_num_p18,p_num_p19,p_num_p21,p_num_p22,p_num_p24
id,,,,,,,,,,,,,,,,,,,,,
p01_test_12,0.650540,1.260560,0.123100,0.123663,0.215425,0.337635,0.429468,0.430034,0.460989,0.461548,...,0,0,0,0,0,0,0,0,0,0
p01_test_13,0.677764,1.246023,0.123100,0.214813,0.337005,0.428855,0.429468,0.460463,0.460989,0.461548,...,0,0,0,0,0,0,0,0,0,0
p01_test_14,0.704663,1.230896,0.214209,0.336345,0.428190,0.428855,0.459886,0.460463,0.460989,0.431109,...,0,0,0,0,0,0,0,0,0,0
p01_test_15,0.731226,1.215187,0.335688,0.427495,0.428190,0.459262,0.459886,0.460463,0.430554,0.431109,...,0,0,0,0,0,0,0,0,0,0
p01_test_16,0.757439,1.198902,0.426798,0.427495,0.458585,0.459262,0.459886,0.430034,0.430554,0.583303,...,0,0,0,0,0,0,0,0,0,0