# Preprocessing

In [1]:
import os
import pandas as pd

data_file = os.path.join('..', '..', '..', '..', 'data', 'raw', 'train.csv')
df = pd.read_csv(data_file, index_col=0, low_memory=False)
df.head()

,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,bg-5:20,...,activity-0:40,activity-0:35,activity-0:30,activity-0:25,activity-0:20,activity-0:15,activity-0:10,activity-0:05,activity-0:00,bg+1:00
id,,,,,,,,,,,,,,,,,,,,,
p01_0,p01,06:10:00,NaN,NaN,9.6,NaN,NaN,9.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.4
p01_1,p01,06:25:00,NaN,NaN,9.7,NaN,NaN,9.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8
p01_2,p01,06:40:00,NaN,NaN,9.2,NaN,NaN,8.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.5
p01_3,p01,06:55:00,NaN,NaN,8.7,NaN,NaN,8.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.8
p01_4,p01,07:10:00,NaN,NaN,8.4,NaN,NaN,8.1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.7

In [2]:
from pipelines import preprocessing_pipeline
df = preprocessing_pipeline.fit_transform(df)
display(df.head())
df.describe()

8.236098761355247
7.6
0.2029884102414185
0.075

,day_phase,bg-5:55,bg-5:50,bg-5:45,bg-5:30,bg-5:25,bg-5:20,bg-5:15,bg-5:10,bg-5:05,...,insulin-0:50,insulin-0:45,insulin-0:30,insulin-0:25,insulin-0:20,insulin-0:15,insulin-0:10,insulin-0:05,insulin-0:00,bg+1:00
id,,,,,,,,,,,,,,,,,,,,,
p01_0,morning,9.6,9.6,9.6,9.7,9.533333,9.366667,9.2,9.033333,8.866667,...,0.0583,0.0583,0.0583,0.0583,0.0583,0.0583,0.0583,0.0417,0.0417,13.4
p01_1,morning,9.7,9.7,9.7,9.2,9.033333,8.866667,8.7,8.600000,8.500000,...,0.0583,0.0583,0.0583,0.0583,0.0417,0.0417,0.0417,0.0417,0.0417,12.8
p01_2,morning,9.2,9.2,9.2,8.7,8.600000,8.500000,8.4,8.300000,8.200000,...,0.0583,0.0583,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,15.5
p01_3,morning,8.7,8.7,8.7,8.4,8.300000,8.200000,8.1,8.166667,8.233333,...,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,14.8
p01_4,morning,8.4,8.4,8.4,8.1,8.166667,8.233333,8.3,8.733333,9.166667,...,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,0.0417,12.7

,bg-5:55,bg-5:50,bg-5:45,bg-5:30,bg-5:25,bg-5:20,bg-5:15,bg-5:10,bg-5:05,bg-5:00,...,insulin-0:50,insulin-0:45,insulin-0:30,insulin-0:25,insulin-0:20,insulin-0:15,insulin-0:10,insulin-0:05,insulin-0:00,bg+1:00
count,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,...,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000
mean,8.281815,8.281229,8.280652,8.279316,8.278834,8.278362,8.277955,8.277567,8.277195,8.276954,...,0.192293,0.193483,0.193439,0.192124,0.192420,0.193530,0.192144,0.192743,0.193257,8.277045
std,3.006360,3.005947,3.003877,3.002576,2.999722,3.000822,3.001121,2.998188,2.999194,2.999518,...,0.990722,0.996247,0.995860,0.988800,0.990094,0.995392,0.988713,0.991087,0.993948,2.996398
min,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,...,-0.307800,-0.307800,-0.307800,-0.307800,-0.307800,-0.307800,-0.307800,-0.307800,-0.307800,2.200000
25%,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,...,0.029200,0.029200,0.029200,0.029200,0.029200,0.029200,0.029200,0.029200,0.029200,6.100000
50%,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,...,0.072900,0.072900,0.072900,0.072900,0.072900,0.072900,0.072900,0.072900,0.072900,7.700000
75%,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,...,0.108300,0.108300,0.108300,0.108300,0.108300,0.108300,0.108300,0.108300,0.108300,9.900000
max,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,...,46.311000,46.311000,46.311000,46.311000,46.311000,46.311000,46.311000,46.311000,46.311000,27.800000

In [5]:
test_data_file = os.path.join('..', '..', '..', '..', 'data', 'raw', 'test.csv')
df_test = pd.read_csv(test_data_file, index_col=0, low_memory=False)
df_test = preprocessing_pipeline.fit_transform(df_test)

8.603584887749774
7.9
0.17988578203396183
0.075

In [4]:
from pipelines import standardization_pipeline
df = standardization_pipeline.fit_transform(df)
display(df.head())
df.describe()

,bg-5:55,bg-5:50,bg-5:45,bg-5:30,bg-5:25,bg-5:20,bg-5:15,bg-5:10,bg-5:05,bg-5:00,...,insulin-0:15,insulin-0:10,insulin-0:05,insulin-0:00,bg+1:00,day_phase_evening,day_phase_late_evening,day_phase_morning,day_phase_night,day_phase_noon
id,,,,,,,,,,,,,,,,,,,,,
p01_0,0.438467,0.438722,0.439216,0.473156,0.418206,0.362670,0.307235,0.252075,0.196544,0.141038,...,-0.135857,-0.135373,-0.152402,-0.15248,13.4,0,0,1,0,0
p01_1,0.471729,0.471989,0.472507,0.306632,0.251524,0.196048,0.140630,0.107543,0.074288,0.041022,...,-0.152533,-0.152162,-0.152402,-0.15248,12.8,0,0,1,0,0
p01_2,0.305415,0.305652,0.306055,0.140108,0.107065,0.073859,0.040667,0.007482,-0.025739,-0.058994,...,-0.152533,-0.152162,-0.152402,-0.15248,15.5,0,0,1,0,0
p01_3,0.139100,0.139315,0.139603,0.040194,0.007056,-0.026113,-0.059296,-0.036989,-0.014625,0.007683,...,-0.152533,-0.152162,-0.152402,-0.15248,14.8,0,0,1,0,0
p01_4,0.039312,0.039512,0.039731,-0.059721,-0.037393,-0.015005,0.007346,0.152014,0.296571,0.441087,...,-0.152533,-0.152162,-0.152402,-0.15248,12.7,0,0,1,0,0

,bg-5:55,bg-5:50,bg-5:45,bg-5:30,bg-5:25,bg-5:20,bg-5:15,bg-5:10,bg-5:05,bg-5:00,...,insulin-0:15,insulin-0:10,insulin-0:05,insulin-0:00,bg+1:00,day_phase_evening,day_phase_late_evening,day_phase_morning,day_phase_night,day_phase_noon
count,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,...,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000
mean,6.678999e-17,7.141391e-16,1.746815e-16,-2.568846e-18,-2.825730e-16,7.231301e-16,-2.414715e-16,2.825730e-17,-9.504729e-17,3.455098e-16,...,-2.183519e-17,3.596384e-17,6.422114e-18,5.266134e-17,8.277045,0.164978,0.081497,0.167853,0.248633,0.168768
std,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,...,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,2.996398,0.371161,0.273598,0.373737,0.432222,0.374548
min,-2.022989e+00,-2.023072e+00,-2.024274e+00,-2.024706e+00,-2.026471e+00,-2.025571e+00,-2.025234e+00,-2.027086e+00,-2.026282e+00,-2.025983e+00,...,-5.036522e-01,-5.056534e-01,-5.050457e-01,-5.041087e-01,2.200000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-7.257353e-01,-7.256400e-01,-7.259481e-01,-7.258175e-01,-7.263474e-01,-7.259236e-01,-7.257157e-01,-7.262965e-01,-7.259290e-01,-7.257702e-01,...,-1.650913e-01,-1.648052e-01,-1.650142e-01,-1.650559e-01,6.100000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,-1.935287e-01,-1.933603e-01,-1.933016e-01,-1.929402e-01,-1.929632e-01,-1.927349e-01,-1.925801e-01,-1.926393e-01,-1.924507e-01,-1.923496e-01,...,-1.211889e-01,-1.206061e-01,-1.209211e-01,-1.210897e-01,7.700000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.382552e-01,5.385243e-01,5.390874e-01,5.397660e-01,5.404402e-01,5.403995e-01,5.404813e-01,5.411395e-01,5.410818e-01,5.411037e-01,...,-8.562493e-02,-8.480190e-02,-8.520263e-02,-8.547407e-02,9.900000,0.000000,0.000000,0.000000,0.000000,0.000000
max,6.492316e+00,6.493403e+00,6.498071e+00,6.501330e+00,6.507676e+00,6.505448e+00,6.504936e+00,6.511430e+00,6.509369e+00,6.508747e+00,...,4.633107e+01,4.664550e+01,4.653312e+01,4.639866e+01,27.800000,1.000000,1.000000,1.000000,1.000000,1.000000