# Preprocessing

In [1]:
import os
import pandas as pd

data_file = os.path.join('..', '..', '..', '..', 'data', 'raw', 'train.csv')
df = pd.read_csv(data_file, index_col=0, low_memory=False)
df.head()

,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,bg-5:20,...,activity-0:40,activity-0:35,activity-0:30,activity-0:25,activity-0:20,activity-0:15,activity-0:10,activity-0:05,activity-0:00,bg+1:00
id,,,,,,,,,,,,,,,,,,,,,
p01_0,p01,06:10:00,NaN,NaN,9.6,NaN,NaN,9.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.4
p01_1,p01,06:25:00,NaN,NaN,9.7,NaN,NaN,9.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8
p01_2,p01,06:40:00,NaN,NaN,9.2,NaN,NaN,8.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.5
p01_3,p01,06:55:00,NaN,NaN,8.7,NaN,NaN,8.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.8
p01_4,p01,07:10:00,NaN,NaN,8.4,NaN,NaN,8.1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.7

In [2]:
from pipelines import preprocessing_pipeline
df = preprocessing_pipeline.fit_transform(df)
display(df.head())
df.describe()

,day_phase,bg-5:45,bg-5:30,bg-5:15,bg-5:00,bg-4:45,bg-4:30,bg-4:15,bg-4:00,bg-3:45,...,bg-2:00,bg-1:45,bg-1:30,bg-1:15,bg-1:00,bg-0:45,bg-0:30,bg-0:15,bg-0:00,bg+1:00
id,,,,,,,,,,,,,,,,,,,,,
p01_0,morning,9.6,9.7,9.2,8.7,8.4,8.1,8.3,9.6,11.1,...,17.2,18.2,18.4,18.0,17.3,17.5,17.3,16.2,15.1,13.4
p01_1,morning,9.7,9.2,8.7,8.4,8.1,8.3,9.6,11.1,11.8,...,18.2,18.4,18.0,17.3,17.5,17.3,16.2,15.1,14.4,12.8
p01_2,morning,9.2,8.7,8.4,8.1,8.3,9.6,11.1,11.8,12.8,...,18.4,18.0,17.3,17.5,17.3,16.2,15.1,14.4,13.9,15.5
p01_3,morning,8.7,8.4,8.1,8.3,9.6,11.1,11.8,12.8,13.9,...,18.0,17.3,17.5,17.3,16.2,15.1,14.4,13.9,13.8,14.8
p01_4,morning,8.4,8.1,8.3,9.6,11.1,11.8,12.8,13.9,14.2,...,17.3,17.5,17.3,16.2,15.1,14.4,13.9,13.8,13.4,12.7

,bg-5:45,bg-5:30,bg-5:15,bg-5:00,bg-4:45,bg-4:30,bg-4:15,bg-4:00,bg-3:45,bg-3:30,...,bg-2:00,bg-1:45,bg-1:30,bg-1:15,bg-1:00,bg-0:45,bg-0:30,bg-0:15,bg-0:00,bg+1:00
count,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,...,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000
mean,8.280652,8.279316,8.277970,8.276979,8.275851,8.275118,8.274538,8.274339,8.274856,8.275430,...,8.279339,8.279266,8.280325,8.281071,8.281502,8.281360,8.279985,8.278990,8.278450,8.277045
std,3.003877,3.002576,3.001113,2.999511,2.997782,2.996343,2.995269,2.994614,2.994453,2.994091,...,2.993727,2.993828,2.995283,2.996314,2.997638,2.998004,2.997691,2.998377,2.998289,2.996398
min,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,...,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000,2.200000
25%,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,...,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000,6.100000
50%,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,...,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000,7.700000
75%,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,...,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000,9.900000
max,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,...,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000,27.800000

In [3]:
from pipelines import standardization_pipeline
df = standardization_pipeline.fit_transform(df)
display(df.head())
df.describe()

,bg-5:45,bg-5:30,bg-5:15,bg-5:00,bg-4:45,bg-4:30,bg-4:15,bg-4:00,bg-3:45,bg-3:30,...,bg-0:45,bg-0:30,bg-0:15,bg-0:00,bg+1:00,day_phase_evening,day_phase_late_evening,day_phase_morning,day_phase_night,day_phase_noon
id,,,,,,,,,,,,,,,,,,,,,
p01_0,0.439216,0.473156,0.307230,0.141031,0.041414,-0.058444,0.008501,0.442683,0.943462,1.177179,...,3.074934,3.008996,2.641773,2.275154,13.4,0,0,1,0,0
p01_1,0.472507,0.306632,0.140625,0.041014,-0.058660,0.008304,0.442520,0.943584,1.177228,1.511171,...,3.008223,2.642046,2.274907,2.041687,12.8,0,0,1,0,0
p01_2,0.306055,0.140108,0.040662,-0.059003,0.008056,0.442168,0.943311,1.177337,1.511180,1.878562,...,2.641311,2.275096,2.041447,1.874925,15.5,0,0,1,0,0
p01_3,0.139603,0.040194,-0.059302,0.007675,0.441711,0.942779,1.177013,1.511271,1.878527,1.978760,...,2.274400,2.041582,1.874690,1.841572,14.8,0,0,1,0,0
p01_4,0.039731,-0.059721,0.007340,0.441080,0.942082,1.176398,1.510874,1.878598,1.978712,1.978760,...,2.040910,1.874787,1.841338,1.708162,12.7,0,0,1,0,0

,bg-5:45,bg-5:30,bg-5:15,bg-5:00,bg-4:45,bg-4:30,bg-4:15,bg-4:00,bg-3:45,bg-3:30,...,bg-0:45,bg-0:30,bg-0:15,bg-0:00,bg+1:00,day_phase_evening,day_phase_late_evening,day_phase_morning,day_phase_night,day_phase_noon
count,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,...,1.770240e+05,1.770240e+05,1.770240e+05,1.770240e+05,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000,177024.000000
mean,1.746815e-16,-2.568846e-18,-4.572545e-16,6.473491e-16,-2.838575e-16,-6.935884e-16,8.091864e-17,-2.864263e-16,-3.300967e-16,-2.491780e-16,...,3.686294e-16,-1.117448e-16,6.589089e-16,4.354194e-16,8.277045,0.164978,0.081497,0.167853,0.248633,0.168768
std,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,...,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,2.996398,0.371161,0.273598,0.373737,0.432222,0.374548
min,-2.024274e+00,-2.024706e+00,-2.025244e+00,-2.025995e+00,-2.026788e+00,-2.027517e+00,-2.028050e+00,-2.028427e+00,-2.028709e+00,-2.029146e+00,...,-2.028475e+00,-2.028229e+00,-2.027432e+00,-2.027312e+00,2.200000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-7.259481e-01,-7.258175e-01,-7.257229e-01,-7.257798e-01,-7.258222e-01,-7.259262e-01,-7.259930e-01,-7.260853e-01,-7.262972e-01,-7.265767e-01,...,-7.276063e-01,-7.272235e-01,-7.267250e-01,-7.265666e-01,6.100000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,-1.933016e-01,-1.929402e-01,-1.925859e-01,-1.923581e-01,-1.920928e-01,-1.919404e-01,-1.918158e-01,-1.917912e-01,-1.919743e-01,-1.921892e-01,...,-1.939164e-01,-1.934778e-01,-1.931015e-01,-1.929274e-01,7.700000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.390874e-01,5.397660e-01,5.404775e-01,5.410968e-01,5.417851e-01,5.422901e-01,5.426779e-01,5.428631e-01,5.427196e-01,5.425936e-01,...,5.399073e-01,5.404224e-01,5.406308e-01,5.408266e-01,9.900000,0.000000,0.000000,0.000000,0.000000,0.000000
max,6.498071e+00,6.501330e+00,6.504948e+00,6.508753e+00,6.512883e+00,6.516257e+00,6.518786e+00,6.520278e+00,6.520457e+00,6.521053e+00,...,6.510563e+00,6.511702e+00,6.510544e+00,6.510916e+00,27.800000,1.000000,1.000000,1.000000,1.000000,1.000000